# Site settings
title: graham's blog
description: > # this means to ignore newlines until "baseurl:"
  graham macdonald's blog of wisdom and doubt
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gmacd.net" # the base hostname & protocol for your site
twitter_username: grimondo
github_username:  gmacd

comments: true

# Build settings
markdown: kramdown
highlighter: pygments
